Upgrade Laravel 6 to Laravel 10 for PHP 8.2 compatibility - Updated composer dependencies - Updated Exception Handler for Laravel 10 - Updated HTTP Kernel middleware structure - Fixed model relationships and removed deprecated features - Created new middleware files - All routes working successfully

diff --git a/vendor/psy/psysh/Makefile b/vendor/psy/psysh/Makefile
--- a/vendor/psy/psysh/Makefile
+++ b/vendor/psy/psysh/Makefile
@@ -1,4 +1,4 @@
-PSYSH_SRC = bin src box.json.dist composer.json build/stub
+PSYSH_SRC = bin src box.json.dist composer.json build/stub scoper.inc.php
 PSYSH_SRC_FILES = $(shell find src -type f -name "*.php")
 VERSION = $(shell git describe --tag --always --dirty=-dev)
 
@@ -6,26 +6,54 @@ COMPOSER_OPTS = --no-interaction --no-progress --verbose
 COMPOSER_REQUIRE_OPTS = $(COMPOSER_OPTS) --no-update
 COMPOSER_UPDATE_OPTS = $(COMPOSER_OPTS) --prefer-stable --no-dev --classmap-authoritative --prefer-dist
 
+ifneq ($(CI),)
+	PHPUNIT_OPTS = --verbose --coverage-clover=coverage.xml
+endif
+
 
 # Commands
 
-.PHONY: help clean build dist
+.PHONY: help build clean dist test test-phar smoketest phpstan
 .DEFAULT_GOAL := help
 
 help:
 	@echo "\033[33mUsage:\033[0m\n  make TARGET\n\n\033[33mTargets:\033[0m"
-	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[32m%-7s\033[0m %s\n", $$1, $$2}'
+	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[32m%-9s\033[0m %s\n", $$1, $$2}'
+
+build: ## Compile psysh PHAR
+build: build/psysh/psysh
 
 clean: ## Clean all created artifacts
 	rm -rf build/*
 	rm -rf dist/*
 	rm -rf vendor-bin/*/vendor/
 
-build: ## Compile PHARs
-build: build/psysh/psysh build/psysh-compat/psysh build/psysh-php54/psysh build/psysh-php54-compat/psysh
-
 dist: ## Build tarballs for distribution
-dist: dist/psysh-$(VERSION).tar.gz dist/psysh-$(VERSION)-compat.tar.gz dist/psysh-$(VERSION)-php54.tar.gz dist/psysh-$(VERSION)-php54-compat.tar.gz
+dist: dist/psysh-$(VERSION).tar.gz
+
+test: ## Run unit tests
+test: vendor/bin/phpunit
+	$< $(PHPUNIT_OPTS)
+
+test-phar: ## Run unit tests with PHAR bootstrap
+test-phar: build/psysh/psysh
+	$(eval PHAR_TEST_DIR := $(shell mktemp -d))
+	@echo "Setting up isolated test environment in $(PHAR_TEST_DIR)..."
+	@cp -r test $(PHAR_TEST_DIR)/
+	@cp $< $(PHAR_TEST_DIR)/
+	@cd $(PHAR_TEST_DIR) && \
+		COMPOSER_ROOT_VERSION=1.0.0 composer init --no-interaction --name=psy/test --autoload=test/ 2>&1 | grep -v "PSR-4" || true && \
+		COMPOSER_ROOT_VERSION=1.0.0 composer require --no-interaction --no-progress "phpunit/phpunit:^9.6" 2>&1 | grep -v "locking\|Extracting" | head -3 || true && \
+		vendor/bin/phpunit --bootstrap psysh --exclude-group isolation-fail test/
+	@rm -rf $(PHAR_TEST_DIR)
+
+smoketest: ## Run smoke tests on existing binaries
+smoketest: build/psysh/psysh
+	test/smoketest.sh
+
+phpstan: ## Run static analysis
+phpstan: vendor/bin/phpstan vendor/bin/phpunit
+	vendor/bin/phpstan --memory-limit=1G analyse
 
 
 # All the composer stuffs
@@ -38,9 +66,21 @@ vendor/autoload.php: composer.lock
 	composer install
 	touch $@
 
-vendor/bin/box: vendor/autoload.php
-	composer bin box install
+vendor-bin/%/vendor/autoload.php: vendor/autoload.php vendor-bin/%/composer.json
+	composer bin $* install
 	touch $@
+
+vendor/bin/box: vendor-bin/box/vendor/autoload.php
+	composer bin box install
+	ln -sf ../../vendor-bin/box/vendor/humbug/box/bin/box $@
+
+vendor/bin/phpunit: vendor-bin/phpunit/vendor/autoload.php
+	composer bin phpunit install --ignore-platform-reqs
+	ln -sf ../../vendor-bin/phpunit/vendor/phpunit/phpunit/phpunit $@
+
+vendor/bin/phpstan: vendor-bin/phpstan/vendor/autoload.php
+	composer bin phpstan install --ignore-platform-reqs
+	ln -sf ../../vendor-bin/phpstan/vendor/phpstan/phpstan/phpstan $@
 
 
 # Lots of PHARs
@@ -52,44 +92,27 @@ build/psysh: $(PSYSH_SRC) $(PSYSH_SRC_FILES)
 	rm -rf $@ || true
 	mkdir $@
 	cp -R $(PSYSH_SRC) $@/
-	composer config --working-dir $@ platform.php 7.0
-	composer require --working-dir $@ $(COMPOSER_REQUIRE_OPTS) php:'>=7.0.0'
-	composer update --working-dir $@ $(COMPOSER_UPDATE_OPTS)
-
-build/psysh-compat: $(PSYSH_SRC) $(PSYSH_SRC_FILES)
-	rm -rf $@ || true
-	mkdir $@
-	cp -R $(PSYSH_SRC) $@/
-	composer config --working-dir $@ platform.php 7.0
-	composer require --working-dir $@ $(COMPOSER_REQUIRE_OPTS) php:'>=7.0.0'
-	composer require --working-dir $@ $(COMPOSER_REQUIRE_OPTS) symfony/polyfill-iconv symfony/polyfill-mbstring hoa/console
-	composer update --working-dir $@ $(COMPOSER_UPDATE_OPTS)
-
-build/psysh-php54: $(PSYSH_SRC) $(PSYSH_SRC_FILES)
-	rm -rf $@ || true
-	mkdir $@
-	cp -R $(PSYSH_SRC) $@/
-	composer config --working-dir $@ platform.php 5.4
-	composer update --working-dir $@ $(COMPOSER_UPDATE_OPTS)
-
-build/psysh-php54-compat: $(PSYSH_SRC) $(PSYSH_SRC_FILES)
-	rm -rf $@ || true
-	mkdir $@
-	cp -R $(PSYSH_SRC) $@/
-	composer config --working-dir $@ platform.php 5.4
-	composer require --working-dir $@ $(COMPOSER_REQUIRE_OPTS) symfony/polyfill-iconv symfony/polyfill-mbstring hoa/console:^2.15
+	@# Fetch and include latest PHP manual
+	@if bin/fetch-manual; then \
+		echo "Including bundled manual..."; \
+		cp php_manual.php $@/; \
+		rm php_manual.php; \
+	else \
+		echo "Manual fetch failed, continuing without bundled manual"; \
+	fi
+	sed -i -e "/^ *const VERSION =/ s/'.*'/'$(VERSION)'/" $@/src/Shell.php
+	composer config --working-dir $@ platform.php 7.4
+	composer require --working-dir $@ $(COMPOSER_REQUIRE_OPTS) php:'>=7.4'
+	composer require --working-dir $@ $(COMPOSER_REQUIRE_OPTS) symfony/polyfill-iconv symfony/polyfill-mbstring composer/class-map-generator
+	composer require --working-dir $@ $(COMPOSER_REQUIRE_OPTS) --dev roave/security-advisories:dev-latest
 	composer update --working-dir $@ $(COMPOSER_UPDATE_OPTS)
 
 build/%/psysh: vendor/bin/box build/%
-	vendor/bin/box compile --working-dir $(dir $@)
+	vendor/bin/box compile --no-parallel --working-dir $(dir $@)
 
 
 # Dist packages
 
 dist/psysh-$(VERSION).tar.gz: build/psysh/psysh
-	@mkdir -p $(@D)
-	tar -C $(dir $<) -czf $@ $(notdir $<)
-
-dist/psysh-$(VERSION)-%.tar.gz: build/psysh-%/psysh
 	@mkdir -p $(@D)
 	tar -C $(dir $<) -czf $@ $(notdir $<)
